name: Build image and deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: ./build_push_image_forum_api.sh
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Create .env file
        run: |
          cat <<EOF > .env
          HOST=${{ secrets.HOST }}
          PORT=${{ secrets.PORT }}
          PGHOST=${{ secrets.PGHOST }}
          PGUSER=${{ secrets.PGUSER }}
          PGDATABASE=${{ secrets.PGDATABASE }}
          PGPASSWORD=${{ secrets.PGPASSWORD }}
          PGPORT=${{ secrets.PGPORT }}
          ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}
          ACCESS_TOKEN_AGE=${{ secrets.ACCESS_TOKEN_AGE }}
          EOF

      - name: Copy docker-compose file to server via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml,.env"
          target: "~"

      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker compose up -d
